theme = "dracula_at_night"

[editor]
cursorline = true
color-modes = true
bufferline = "multiple" 
auto-save = true
auto-format = true
auto-info = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true

[keys.normal]
# "A-/" = "toggle_comments"
"C-/" = "toggle_comments"
"C-c" = "no_op"

