[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py"]
shebangs = ["python"]
comment-token = "#"
indent = { tab-width = 4, unit = "    " }
language-servers = [ "pylsp" ]