#!/bin/env python3

import sys
import os

match (len(sys.argv)):
    case 1:
        print("Usage: ", sys.argv[0], " <url> <method> <params>")
        exit()
    case 2:
        os.system(' '.join(["xh", sys.argv[1]]))
        exit()
        

url = sys.argv[1]
method = sys.argv[2]
args = sys.argv[3:]

xh_cmd = ["xh", "-6", method, url] + args
xh_cmd = ' '.join(xh_cmd)

print("Executing: ", xh_cmd)
os.system(xh_cmd)
